name: Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://hawkingrei/tind:v5.2.1
        name: __all__
        with:
          args: |
            bash -c "tox -e lint"
